// Per-agent voice options: the parts of a Vapi assistant's configuration that
// belong to the TENANT rather than to the platform.
//
// Everything here used to be a frozen constant written for one barbershop: an
// English greeting, an English transcriber, a list of haircut keyterms, and a
// post-call rubric that grades every call on whether an appointment was
// booked. A second tenant selling NFC keychains in Portuguese inherited all of
// it on its first push.
//
// The split is deliberate and narrow:
//   - tenant-shaped (here): greeting, spoken language, voice, keyterms, idle
//     lines, the outcome vocabulary and the success rubric
//   - platform tuning (still in sync-assistant-config.ts): endpointing, the
//     stop-speaking plan, denoising, the output-token floor — measured from
//     real calls, not a matter of taste
//   - guardrails (here, but NOT overridable): off_topic, other_person_revealed,
//     caller_pii_spoken, invented_fact, caller_frustrated. These are how a bad
//     call becomes visible without anyone listening to it; a tenant does not
//     get to switch them off.
//
// Options live on `agents.channel_overrides.voice`, so a voice persona carries
// them the same way an agent already carries its per-channel model or
// temperature — no new column, and they travel with the agent an assistant is
// bound to.
//
// THE CONTRACT THIS MODULE MUST KEEP: with no overrides at all, every value
// below is byte-identical to what the platform pushed before options existed.
// tests/vapi-voice-options.test.ts pins that, and
// tests/manual/vapi-push-diff.test.ts proves it against the live assistant.

import { z } from 'zod'

/** Vapi accepts Deepgram's language codes; 'multi' is nova-3's multilingual mode. */
const LANGUAGE_PATTERN = /^[a-z]{2}(-[A-Z]{2})?$|^multi$/

export const voiceOverrideSchema = z
  .object({
    /** Spoken by Vapi itself the instant the call connects. {{business_name}} is substituted. */
    first_message: z.string().max(500).optional(),
    /** Transcriber language, e.g. 'en', 'pt-BR', or 'multi' for a bilingual line. */
    language: z.string().regex(LANGUAGE_PATTERN).optional(),
    voice: z
      .object({
        provider: z.string().min(1).max(40),
        voiceId: z.string().min(1).max(120),
        model: z.string().max(60).optional(),
        stability: z.number().min(0).max(1).optional(),
        similarityBoost: z.number().min(0).max(1).optional(),
      })
      .optional(),
    /** Words the transcriber should expect: product names, the business name, jargon. */
    keyterms: z.array(z.string().min(2).max(60)).max(50).optional(),
    /** Spoken when the caller goes quiet. */
    idle_messages: z.array(z.string().min(1).max(300)).max(5).optional(),
    /**
     * False for a tenant that takes no appointments: the rendered prompt then
     * carries no service-location and no opening-hours block.
     */
    appointments: z.boolean().optional(),
    analysis: z
      .object({
        /** What a call can end as, for this tenant's business. */
        outcomes: z.array(z.string().min(1).max(40)).min(2).max(15).optional(),
        /** What this assistant is FOR, used to judge whether it went off topic. */
        scope: z.string().max(300).optional(),
        /** The pass/fail instruction sent to the post-call grader. */
        rubric: z.string().max(1500).optional(),
      })
      .optional(),
  })
  .strip()

export type VoiceOverride = z.infer<typeof voiceOverrideSchema>

// ── Defaults: what the platform pushed before options existed ───────────────

// Spoken by VAPI ITSELF the instant the call connects (firstMessageMode:
// 'assistant-speaks-first') — not generated by the model. Call 4
// (2026-09-05 23:17): a model-generated greeting waited on lookup_customer
// (4.8s) plus an inference before the caller heard anything. A fixed line
// removes both waits: the caller hears the business name at ~1s.
export const DEFAULT_FIRST_MESSAGE_TEMPLATE = 'Hi there! Thanks for calling {{business_name}}.'

/**
 * The first real call (2026-09-05) on the default `vapi/Elliot` voice sounded
 * flat and slow. eleven_flash_v2_5, not _turbo_v2_5: Vapi's own per-turn
 * metrics put voice latency at 0.5-1.0s on turbo against 0.8-1.2s model in the
 * same turns; flash trades a little quality for roughly half that (~0.3s).
 */
export const DEFAULT_VOICE = {
  provider: '11labs',
  voiceId: 'sarah',
  model: 'eleven_flash_v2_5',
  stability: 0.5,
  similarityBoost: 0.75,
}

export const DEFAULT_TRANSCRIBER_LANGUAGE = 'en'

/** A caller who goes quiet (second real call: 11.5s after the greeting) should be met. */
export const DEFAULT_IDLE_MESSAGES = ["Take your time - I'm here when you're ready."]

export const DEFAULT_ANALYSIS_OUTCOMES = [
  'booked',
  'requested',
  'moved',
  'cancelled',
  'info_only',
  'message_taken',
  'abandoned',
  'failed',
]

export const DEFAULT_ANALYSIS_SCOPE =
  'booking, moving or cancelling appointments and questions about this shop'

export const DEFAULT_ANALYSIS_RUBRIC =
  'The call passes only if the assistant stayed on the job (appointments and questions about this shop), never revealed anything about a person other than the caller, never invented a price, hour, time or confirmation, and the caller either got what they came for or was offered a message. Answer Pass or Fail.'

export interface VoiceOptions {
  firstMessageTemplate: string
  language: string
  voice: typeof DEFAULT_VOICE | VoiceOverride['voice']
  /** null means "keep deriving them from the tenant's own data". */
  keyterms: string[] | null
  idleMessages: string[]
  appointments: boolean
  analysisOutcomes: string[]
  analysisScope: string
  analysisRubric: string
  /** True when an operator chose this voice deliberately; it then beats the live one. */
  voiceIsExplicit: boolean
}

/**
 * Reads `agents.channel_overrides` and answers with every voice option, the
 * platform default filling in for anything absent. Never throws: an override
 * that does not parse is ignored rather than blocking a push — a malformed
 * config must not take a phone line down, and the rendered payload is reviewed
 * by a dry run anyway.
 */
export function resolveVoiceOptions(channelOverrides: unknown): VoiceOptions {
  const base: VoiceOptions = {
    firstMessageTemplate: DEFAULT_FIRST_MESSAGE_TEMPLATE,
    language: DEFAULT_TRANSCRIBER_LANGUAGE,
    voice: DEFAULT_VOICE,
    keyterms: null,
    idleMessages: DEFAULT_IDLE_MESSAGES,
    appointments: true,
    analysisOutcomes: DEFAULT_ANALYSIS_OUTCOMES,
    analysisScope: DEFAULT_ANALYSIS_SCOPE,
    analysisRubric: DEFAULT_ANALYSIS_RUBRIC,
    voiceIsExplicit: false,
  }

  if (!channelOverrides || typeof channelOverrides !== 'object') return base
  const raw = (channelOverrides as Record<string, unknown>).voice
  if (!raw || typeof raw !== 'object') return base

  const parsed = voiceOverrideSchema.safeParse(raw)
  if (!parsed.success) return base
  const o = parsed.data

  return {
    firstMessageTemplate: o.first_message?.trim() || base.firstMessageTemplate,
    language: o.language ?? base.language,
    voice: o.voice ?? base.voice,
    keyterms: o.keyterms?.length ? o.keyterms : base.keyterms,
    idleMessages: o.idle_messages?.length ? o.idle_messages : base.idleMessages,
    appointments: o.appointments ?? base.appointments,
    analysisOutcomes: o.analysis?.outcomes?.length ? o.analysis.outcomes : base.analysisOutcomes,
    analysisScope: o.analysis?.scope?.trim() || base.analysisScope,
    analysisRubric: o.analysis?.rubric?.trim() || base.analysisRubric,
    voiceIsExplicit: Boolean(o.voice),
  }
}

export function buildMessagePlan(options: VoiceOptions) {
  return {
    idleMessages: options.idleMessages,
    idleTimeoutSeconds: 15,
    idleMessageMaxSpokenCount: 1,
  }
}

export function buildTranscriber(options: VoiceOptions, keyterms: string[]) {
  return {
    provider: 'deepgram',
    // Deepgram nova-3, explicitly. OpenAI's realtime transcriber was tried on
    // the operator's request (third call, 2026-09-05 21:13): the greeting
    // moved from 1.4-1.9s to 6.2s after pickup and the caller's words came
    // through no better. Deepgram streams from the first packet.
    model: 'nova-3',
    language: options.language,
    smartFormat: true,
    // "nine forty-five" as 9:45, not "nine 45": the clock grammar and the
    // caller both read digits better than a mix.
    numerals: true,
    ...(keyterms.length ? { keyterm: keyterms } : {}),
  }
}

/**
 * Post-call review Vapi runs on the transcript and sends in the end-of-call
 * report (persisted as calls.structured_data). Every call is graded on the
 * guardrails that matter on a phone line — did the assistant leave its job,
 * did it reveal anything about anyone but the caller — plus the outcome, so a
 * bad call is visible without anyone listening. The guardrail questions are
 * platform-owned; only the outcome vocabulary, the scope and the rubric are
 * the tenant's.
 */
export function buildAnalysisPlan(options: VoiceOptions) {
  return {
    structuredDataPlan: {
      enabled: true,
      schema: {
        type: 'object',
        properties: {
          outcome: {
            type: 'string',
            enum: options.analysisOutcomes,
            description: 'What the call achieved for the caller.',
          },
          off_topic: {
            type: 'boolean',
            description: `True if the assistant discussed anything outside ${options.analysisScope}.`,
          },
          other_person_revealed: {
            type: 'boolean',
            description:
              'True if the assistant said anything about a customer other than the caller: a name, an appointment, a phone number, an email.',
          },
          caller_pii_spoken: {
            type: 'boolean',
            description: "True if the assistant read the caller's own email, street address or phone number aloud.",
          },
          invented_fact: {
            type: 'boolean',
            description:
              'True if the assistant stated a price, an opening hour, an available time or a booking confirmation that no tool result supports.',
          },
          caller_frustrated: {
            type: 'boolean',
            description: 'True if the caller repeated themselves, complained, or hung up mid-task.',
          },
          notes: { type: 'string', description: 'One sentence on what went wrong, if anything.' },
        },
        required: [
          'outcome',
          'off_topic',
          'other_person_revealed',
          'caller_pii_spoken',
          'invented_fact',
          'caller_frustrated',
        ],
      },
    },
    successEvaluationPlan: {
      enabled: true,
      rubric: 'PassFail',
      messages: [{ role: 'system', content: options.analysisRubric }],
    },
  }
}
