-- =============================================================================
-- Migration 1046: Traffic Module — Website Tracking & UTM Analytics
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Section 1: traffic_setups
-- One row per organization. Tracks installation state and script token.
-- ---------------------------------------------------------------------------

CREATE TABLE public.traffic_setups (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id     UUID        NOT NULL UNIQUE REFERENCES public.organizations(id) ON DELETE CASCADE,
  script_token        TEXT        NOT NULL UNIQUE DEFAULT encode(gen_random_bytes(24), 'hex'),
  primary_website_url TEXT,
  verification_state  TEXT        NOT NULL DEFAULT 'not_started'
                      CHECK (verification_state IN ('not_started','pending','verified','failed','no_events_yet')),
  verified_at         TIMESTAMPTZ,
  gtm_container_id    TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.traffic_setups ENABLE ROW LEVEL SECURITY;

CREATE POLICY "traffic_setups_select" ON public.traffic_setups
  FOR SELECT TO authenticated
  USING (organization_id = (SELECT public.get_current_org_id()));

CREATE POLICY "traffic_setups_insert" ON public.traffic_setups
  FOR INSERT TO authenticated
  WITH CHECK (organization_id = (SELECT public.get_current_org_id()));

CREATE POLICY "traffic_setups_update" ON public.traffic_setups
  FOR UPDATE TO authenticated
  USING (organization_id = (SELECT public.get_current_org_id()));

DROP TRIGGER IF EXISTS trg_traffic_setups_set_updated_at ON public.traffic_setups;
CREATE TRIGGER trg_traffic_setups_set_updated_at
  BEFORE UPDATE ON public.traffic_setups
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ---------------------------------------------------------------------------
-- Section 2: traffic_visitors
-- Anonymous visitor fingerprints. visitor_id comes from a persistent cookie
-- set by the tracking script. Identified when linked to a contact.
-- ---------------------------------------------------------------------------

CREATE TABLE public.traffic_visitors (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  visitor_key      TEXT        NOT NULL,
  first_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  session_count    INTEGER     NOT NULL DEFAULT 0,
  page_view_count  INTEGER     NOT NULL DEFAULT 0,
  is_identified    BOOLEAN     NOT NULL DEFAULT false,
  contact_id       UUID        REFERENCES public.contacts(id) ON DELETE SET NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (organization_id, visitor_key)
);

ALTER TABLE public.traffic_visitors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "traffic_visitors_select" ON public.traffic_visitors
  FOR SELECT TO authenticated
  USING (organization_id = (SELECT public.get_current_org_id()));

CREATE INDEX idx_traffic_visitors_org ON public.traffic_visitors (organization_id);
CREATE INDEX idx_traffic_visitors_contact ON public.traffic_visitors (contact_id) WHERE contact_id IS NOT NULL;

DROP TRIGGER IF EXISTS trg_traffic_visitors_set_updated_at ON public.traffic_visitors;
CREATE TRIGGER trg_traffic_visitors_set_updated_at
  BEFORE UPDATE ON public.traffic_visitors
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ---------------------------------------------------------------------------
-- Section 3: traffic_sessions
-- One row per browser session. Captures UTM attribution, device, geo, referrer.
-- session_key is a UUID generated by the tracking script per session.
-- ---------------------------------------------------------------------------

CREATE TABLE public.traffic_sessions (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  visitor_id       UUID        NOT NULL REFERENCES public.traffic_visitors(id) ON DELETE CASCADE,
  session_key      TEXT        NOT NULL,
  started_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at         TIMESTAMPTZ,
  page_view_count  INTEGER     NOT NULL DEFAULT 0,
  duration_seconds INTEGER,
  landing_page     TEXT,
  exit_page        TEXT,
  referrer         TEXT,
  -- UTM attribution
  utm_source       TEXT,
  utm_medium       TEXT,
  utm_campaign     TEXT,
  utm_term         TEXT,
  utm_content      TEXT,
  -- Geo (privacy-conscious: city/country only, no precise coordinates)
  country_code     TEXT,
  country_name     TEXT,
  city             TEXT,
  -- Device
  device_type      TEXT        CHECK (device_type IN ('desktop','mobile','tablet','unknown')),
  browser          TEXT,
  os               TEXT,
  -- Conversion
  is_converted     BOOLEAN     NOT NULL DEFAULT false,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (organization_id, session_key)
);

ALTER TABLE public.traffic_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "traffic_sessions_select" ON public.traffic_sessions
  FOR SELECT TO authenticated
  USING (organization_id = (SELECT public.get_current_org_id()));

CREATE INDEX idx_traffic_sessions_org ON public.traffic_sessions (organization_id);
CREATE INDEX idx_traffic_sessions_visitor ON public.traffic_sessions (visitor_id);
CREATE INDEX idx_traffic_sessions_started_at ON public.traffic_sessions (organization_id, started_at DESC);
CREATE INDEX idx_traffic_sessions_utm_campaign ON public.traffic_sessions (organization_id, utm_campaign) WHERE utm_campaign IS NOT NULL;

DROP TRIGGER IF EXISTS trg_traffic_sessions_set_updated_at ON public.traffic_sessions;
CREATE TRIGGER trg_traffic_sessions_set_updated_at
  BEFORE UPDATE ON public.traffic_sessions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ---------------------------------------------------------------------------
-- Section 4: traffic_pageviews
-- One row per page view. Linked to session and visitor.
-- ---------------------------------------------------------------------------

CREATE TABLE public.traffic_pageviews (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  session_id       UUID        NOT NULL REFERENCES public.traffic_sessions(id) ON DELETE CASCADE,
  visitor_id       UUID        NOT NULL REFERENCES public.traffic_visitors(id) ON DELETE CASCADE,
  url              TEXT        NOT NULL,
  path             TEXT        NOT NULL,
  title            TEXT,
  referrer         TEXT,
  duration_seconds INTEGER,
  occurred_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.traffic_pageviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "traffic_pageviews_select" ON public.traffic_pageviews
  FOR SELECT TO authenticated
  USING (organization_id = (SELECT public.get_current_org_id()));

CREATE INDEX idx_traffic_pageviews_org_occurred ON public.traffic_pageviews (organization_id, occurred_at DESC);
CREATE INDEX idx_traffic_pageviews_session ON public.traffic_pageviews (session_id);
CREATE INDEX idx_traffic_pageviews_path ON public.traffic_pageviews (organization_id, path);

-- ---------------------------------------------------------------------------
-- Section 5: traffic_events
-- Conversion and custom events captured by the tracking script or server-side.
-- event_type is a known set; custom events use type='custom_conversion' + event_name.
-- ---------------------------------------------------------------------------

CREATE TABLE public.traffic_events (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  session_id       UUID        REFERENCES public.traffic_sessions(id) ON DELETE SET NULL,
  visitor_id       UUID        REFERENCES public.traffic_visitors(id) ON DELETE SET NULL,
  event_type       TEXT        NOT NULL
                   CHECK (event_type IN (
                     'form_submit','phone_click','sms_click','call_started',
                     'chat_started','booking_started','booking_completed',
                     'contact_created','opportunity_created','deal_won','custom_conversion'
                   )),
  event_name       TEXT,
  url              TEXT,
  metadata         JSONB       NOT NULL DEFAULT '{}',
  contact_id       UUID        REFERENCES public.contacts(id) ON DELETE SET NULL,
  opportunity_id   UUID        REFERENCES public.opportunities(id) ON DELETE SET NULL,
  occurred_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.traffic_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "traffic_events_select" ON public.traffic_events
  FOR SELECT TO authenticated
  USING (organization_id = (SELECT public.get_current_org_id()));

CREATE INDEX idx_traffic_events_org_occurred ON public.traffic_events (organization_id, occurred_at DESC);
CREATE INDEX idx_traffic_events_session ON public.traffic_events (session_id) WHERE session_id IS NOT NULL;
CREATE INDEX idx_traffic_events_type ON public.traffic_events (organization_id, event_type);

-- ---------------------------------------------------------------------------
-- Section 6: traffic_attributions
-- First-touch and last-touch attribution records per visitor.
-- One first row and one last row per visitor (upserted on each session).
-- ---------------------------------------------------------------------------

CREATE TABLE public.traffic_attributions (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  UUID        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  visitor_id       UUID        NOT NULL REFERENCES public.traffic_visitors(id) ON DELETE CASCADE,
  touch_type       TEXT        NOT NULL CHECK (touch_type IN ('first','last')),
  utm_source       TEXT,
  utm_medium       TEXT,
  utm_campaign     TEXT,
  utm_term         TEXT,
  utm_content      TEXT,
  landing_page     TEXT,
  referrer         TEXT,
  session_id       UUID        REFERENCES public.traffic_sessions(id) ON DELETE SET NULL,
  occurred_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (visitor_id, touch_type)
);

ALTER TABLE public.traffic_attributions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "traffic_attributions_select" ON public.traffic_attributions
  FOR SELECT TO authenticated
  USING (organization_id = (SELECT public.get_current_org_id()));

CREATE INDEX idx_traffic_attributions_visitor ON public.traffic_attributions (visitor_id);
CREATE INDEX idx_traffic_attributions_org ON public.traffic_attributions (organization_id);

DROP TRIGGER IF EXISTS trg_traffic_attributions_set_updated_at ON public.traffic_attributions;
CREATE TRIGGER trg_traffic_attributions_set_updated_at
  BEFORE UPDATE ON public.traffic_attributions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
