-- =============================================================================
-- Migration 1147: Public API Keys
--
-- Introduces the api_keys table so external apps (form sites, webhooks, etc.)
-- can push contacts into Xphere via POST /api/v1/contacts using a Bearer token.
--
-- Design:
--   * Full token is never stored — only SHA-256 hash + display prefix (12 chars)
--   * RLS lets org members manage their own keys via the settings page
--   * Service-role client (no RLS) is used by the API endpoint for hash lookups
--   * Partial index on (key_hash) WHERE revoked_at IS NULL for fast auth
-- =============================================================================

-- ----- api_keys table ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.api_keys (
  id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id       uuid        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name         text        NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
  key_hash     text        NOT NULL UNIQUE,
  key_prefix   text        NOT NULL,
  scopes       text[]      NOT NULL DEFAULT '{"contacts:write"}',
  created_by   uuid        REFERENCES auth.users(id) ON DELETE SET NULL,
  last_used_at timestamptz,
  revoked_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);

-- Fast hash lookup on auth path (only active keys)
CREATE UNIQUE INDEX IF NOT EXISTS idx_api_keys_hash_active
  ON public.api_keys (key_hash)
  WHERE revoked_at IS NULL;

-- Reverse listing for the settings page
CREATE INDEX IF NOT EXISTS idx_api_keys_org_id
  ON public.api_keys (org_id, created_at DESC);

COMMENT ON TABLE public.api_keys IS
  'Bearer-token credentials for the public REST API (/api/v1/*). '
  'Full token is never stored — only its SHA-256 hash. '
  'Service-role bypasses RLS for auth lookups; RLS lets org members manage keys.';

-- ----- RLS -------------------------------------------------------------------

ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS api_keys_org_isolation ON public.api_keys;
CREATE POLICY api_keys_org_isolation ON public.api_keys
  FOR ALL TO authenticated
  USING      (org_id = (SELECT public.get_current_org_id()))
  WITH CHECK (org_id = (SELECT public.get_current_org_id()));

-- ----- Add 'api' to contacts.source CHECK ------------------------------------
-- The existing inline CHECK constraint name is auto-generated by Postgres as
-- contacts_source_check. Drop and recreate to extend the allowed values.
-- Also adds 'facebook' and 'messenger' which were in the TS type but missing
-- from the SQL constraint.

ALTER TABLE public.contacts
  DROP CONSTRAINT IF EXISTS contacts_source_check;

ALTER TABLE public.contacts
  ADD CONSTRAINT contacts_source_check
    CHECK (source IN (
      'manual',
      'whatsapp',
      'sms',
      'instagram',
      'facebook',
      'messenger',
      'csv_import',
      'ghl_sync',
      'api'
    ));
