-- 1204_website_analyses.sql
-- NOTE: ProspectEventType enum does not exist in production (event_type in
-- prospect_engagement_events is plain text). The ALTER TYPE line below is a
-- no-op stub kept for documentation; it was omitted when this migration was
-- applied to production via the Supabase MCP on 2026-06-08.
-- The string value 'website_analyzed' works fine as plain text.

-- ALTER TYPE public."ProspectEventType" ADD VALUE IF NOT EXISTS 'website_analyzed';

-- Stores the output of the Website Analyzer (Playwright) for the Active Prospect System.
-- One row per account per run; the latest completed row is the "current" analysis.

CREATE TABLE IF NOT EXISTS public.website_analyses (
  id                      uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  org_id                  uuid        NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  account_id              uuid        NOT NULL REFERENCES public.accounts(id)      ON DELETE CASCADE,
  status                  text        NOT NULL DEFAULT 'pending'
                                      CHECK (status IN ('pending', 'running', 'completed', 'failed')),
  url                     text,
  -- Extracted data
  lead_score              integer     CHECK (lead_score BETWEEN 0 AND 100),
  brand_colors            jsonb       NOT NULL DEFAULT '[]'::jsonb,
  logo_url                text,
  services                text[]      NOT NULL DEFAULT '{}',
  pain_points             text[]      NOT NULL DEFAULT '{}',
  -- Screenshots stored in Supabase Storage (bucket: website-screenshots)
  screenshot_desktop_url  text,
  screenshot_mobile_url   text,
  -- Preview generated by skaleclub-websites
  preview_url             text,
  preview_token           text,
  -- Full evidence bundle for Hermes / preview generator
  raw_evidence            jsonb       NOT NULL DEFAULT '{}'::jsonb,
  -- Error (if status = 'failed')
  error_message           text,
  -- Timestamps
  analyzed_at             timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS website_analyses_account_id_idx ON public.website_analyses (account_id);
CREATE INDEX IF NOT EXISTS website_analyses_org_status_idx  ON public.website_analyses (org_id, status);

-- RLS (app role bypasses this — defense-in-depth only)
ALTER TABLE public.website_analyses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "org members can read website_analyses" ON public.website_analyses;
CREATE POLICY "org members can read website_analyses"
  ON public.website_analyses FOR SELECT
  USING (org_id = (SELECT get_current_org_id()));
